version: "3"
services: 
  web:
    build: .
    ports: 
      - "8080:8080"
    environment: 
      - PORT=8080
    # volumes: 
    #   - .:/usr/src/docde
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"
