# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:17.05.0-ce-git

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/docde

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            # curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            # chmod +x ~/docker-compose
            # sudo mv ~/docker-compose /usr/local/bin/docker-compose
            #image: docker:17.05.0-ce-git
            apk add --no-cache py-pip
            pip install docker-compose==1.23.2
            # sudo apt update
            # sudo apt install -y python-pip
            # pip install docker-compose==1.23.2

      - run:
          name: Build Services & Testing
          command: |
            docker-compose up -d
            docker-compose run web npm test

      # - run:
      #     name: Push to DockerHub
      #     command: |
      #       docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
      #       docker push mlabouardy/movies-store:$CIRCLE_SHA1
      # - run:
      #     name: Setup Heroku
      #     command: |
      #       chmod +x .circleci/setup-heroku.sh
      #       .circleci/setup-heroku.sh
      # - run:
      #     name: Deploy to Heroku
      #     command: |
      #       git push origin master
      # deploy the image
      - run:
          name: Login docker & push to registry heroku
          command: |
            docker login -username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag docde_web registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Setup Heroku
          command: |
            chmod a+x .circleci/setup-heroku.sh
            cat .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME

#   deploy:
#     docker:
#       - image: buildpack-deps:trusty
#     steps:
#       - checkout
#       - run:
#           name: Deploy Master to Heroku
#           command: |
#             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
            